site_name: bajiecc
site_url: https://www.gohh.top/
site_description: '八戒的小店'
copyright: 'copyrights by yichi zhang'
nav:
    - Home: index.md
    - About: about.md
theme:
    name: material
    locale: zh_CN
    nav_style: dark
